### ISSUE TITLE
ValueError: invalid literal for int() with base 10: ','

### ISSUE THREAD

**Issue by SeekPoint** [billy-inn/NFETC#2]
mldl@ub1604:~/ub16_prj/NFETC$ python3 task.py -m best_nfetc_wiki  -d wiki
Loading data...
Traceback (most recent call last):
  File "task.py", line 306, in <module>
    main(options)
  File "task.py", line 301, in main
    optimizer.run()
  File "task.py", line 274, in run
    best = fmin(self._obj, self.model_param_space._build_space(), tpe.suggest, self.max_evals, trials)
  File "/usr/local/lib/python3.5/dist-packages/hyperopt/fmin.py", line 367, in fmin
    return_argmin=return_argmin,
  File "/usr/local/lib/python3.5/dist-packages/hyperopt/base.py", line 635, in fmin
    return_argmin=return_argmin)
  File "/usr/local/lib/python3.5/dist-packages/hyperopt/fmin.py", line 385, in fmin
    rval.exhaust()
  File "/usr/local/lib/python3.5/dist-packages/hyperopt/fmin.py", line 244, in exhaust
    self.run(self.max_evals - n_done, block_until_done=self.asynchronous)
  File "/usr/local/lib/python3.5/dist-packages/hyperopt/fmin.py", line 218, in run
    self.serial_evaluate()
  File "/usr/local/lib/python3.5/dist-packages/hyperopt/fmin.py", line 137, in serial_evaluate
    result = self.domain.evaluate(spec, ctrl)
  File "/usr/local/lib/python3.5/dist-packages/hyperopt/base.py", line 840, in evaluate
    rval = self.fn(pyll_rval)
  File "task.py", line 259, in _obj
    self.task = Task(self.model_name, self.data_name, self.cv_runs, param_dict, self.logger)
  File "task.py", line 50, in __init__
    self.embedding = embedding_utils.Embedding.fromCorpus(config.EMBEDDING_DATA, list(words_train)+list(words), config.MAX_DOCUMENT_LENGTH, config.MENTION_SIZE)
  File "/home/mldl/ub16_prj/NFETC/utils/embedding_utils.py", line 27, in fromCorpus
    model = gensim.models.KeyedVectors.load_word2vec_format(f, binary=False)
  File "/usr/local/lib/python3.5/dist-packages/gensim/models/keyedvectors.py", line 203, in load_word2vec_format
    vocab_size, vector_size = (int(x) for x in header.split())  # throws for invalid file format
  File "/usr/local/lib/python3.5/dist-packages/gensim/models/keyedvectors.py", line 203, in <genexpr>
    vocab_size, vector_size = (int(x) for x in header.split())  # throws for invalid file format
ValueError: invalid literal for int() with base 10: ','

**Comment by billy-inn** [comment]
Add one more line "2196017 300" to the head of glove.840.300d.txt
